name: Test Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    uses: evanwon/extension-workflows/.github/workflows/test-pr.yml@v1
    with:
      lint-warnings-as-errors: false
      validate-versions: false
      security-audit-strict: false
      upload-coverage: false
